### ISSUE TITLE
main.js 文件下面 methods方法 都是多余的，可以写到vuex里

### ISSUE THREAD

**Issue by wwb568109135** [bxm0927/vue-xiaomi-website#2]
methods:{
    checkLogin(){
      axios.get("users/checkLogin").then(res=> {
        var res = res.data;
        if (res.status == "0") {
          this.$store.commit("updateUserInfo", res.result);
        }else{
          if(this.$route.path!="/goods"){
            this.$router.push("/goods");
          }
        }
      });
    },
    getCartCount(){
      axios.get("users/getCartCount").then(res=>{
        var res = res.data;
        if(res.status=="0"){
          this.$store.commit("updateCartCount",res.result);
        }
      });
    }
  },

**Comment by bxm0927** [comment]
谢谢提醒 ^_^，由于需要集中管理的状态就几个，就没有抽离出来
